[package]
name = "dibrova"
version = "0.1.0"
authors = ["Kostia Balytskyi <kostia.balitsky@gmail.com>"]
edition = "2018"

[lib]
name = "dibrova"
path = "src/lib.rs"

[[bin]]
name = "dsu-benchmark"
path = "src/dsu-benchmark.rs"

[dependencies]
rand = "*"